# Minecraft
minecraft.version=1.21.1

# NeoForge
neoforge.version=21.1.82
neoforge.parchment.minecraft_version=1.21.1
neoforge.parchment.version=2024.11.17

# Forge
forge.version=52.0.28
forge.mapping_channel=parchment
forge.mapping=1.21.1-2024.11.17-1.21.1

# Fabric
fabric.loader.version=0.16.9
fabric.api.version=0.110.0+1.21.1
fabric.mapping_layer=org.parchmentmc.data:parchment-1.21.1:2024.11.17@zip

# Mod
mod.version=5.6.0
mod.snapshot=false
mod.filename=u_team_core
mod.name=U Team Core
mod.modid=uteamcore

# Publish
publish.type=stable
publish.display=U-Team-Core

# Curse
curse.id=273744
curse.slug=u-team-core

# Modrinth
modrinth.id=g2FGQs4R

# Github
github.name=U-Team-Core
github.branch=1.21.1

# Dependencies
jei.version=19.3.1.25
modmenu.fabric.version=11.0.3