modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/MC-U-Team/U-Team-Core/issues"
displayURL="https://u-team.info/mods/uteamcore"
license="Apache-2.0 License"
credits="Team U-Team"
authors="HyCraftHD"
    
[[mods]]
	modId="uteamtest"
	version="1.0.0"
	displayName="U Team Test"
	description="This is just a test mod to test uteamcore"
	
	[[dependencies.uteamtest]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="${file.jarVersion}"
	    ordering="NONE"
	    side="BOTH"
	    
[[mods]]
	modId="uteamtest2"
	version="1.0.0"
	displayName="U Team Test 2"
	description="This is just a test mod 2 for some other stuff"
	
	[[dependencies.uteamtest2]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="${file.jarVersion}"
	    ordering="NONE"
	    side="BOTH"