modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MC-U-Team/U-Team-Core/issues"
displayURL="https://u-team.info/mods/uteamcore"
credits="Team U-Team"
authors="HyCraftHD"
    
[[mods]]
	modId="uteamtest"
	version="1.0.0"
	displayName="U Team Test"
	description="This is just a test mod to test uteamcore"
	
	[[dependencies.uteamtest]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="${file.jarVersion}"
	    ordering="NONE"
	    side="BOTH"