modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/MC-U-Team/U-Team-Core/issues"
license="Apache-2.0 License"
    
[[mods]]
	modId="uteamtest"
	version="${file.jarVersion}"
	displayName="U Team Test"
	displayURL="https://u-team.info/mods/uteamcore"
	credits="Team U-Team"
	authors="HyCraftHD"
	description="This is just a test mod to test uteamcore"
	
	[[dependencies.uteamtest]]
	    modId="uteamcore"
	    type="required"
	    versionRange="${file.jarVersion}"
	    ordering="NONE"
	    side="BOTH"
	    
[[mods]]
	modId="uteamtest2"
	version="${file.jarVersion}"
	displayName="U Team Test 2"
	displayURL="https://u-team.info/mods/uteamcore"
	credits="Team U-Team"
	authors="HyCraftHD"
	description="This is just a test mod 2 for some other stuff"
	
	[[dependencies.uteamtest2]]
	    modId="uteamcore"
	    type="required"
	    versionRange="${file.jarVersion}"
	    ordering="NONE"
	    side="BOTH"