plugins {
	id "info.u_team.gradle_files"
}

gradlefiles.loaderSuffix = "neoforge-coremod"

group = rootProject.group
base.archivesName = gradlefiles.archivesName()
version = gradlefiles.version()

sourceSets {
	main {
		java
		resources
	}
}

java {
	toolchain {
		languageVersion = gradlefiles.project("neoforge").java.toolchain.languageVersion
	}
}

tasks.withType(Jar).configureEach { task ->
	gradlefiles.defaultJar(task)
	
	manifest {
		attributes("Automatic-Module-Name": "info.u_team.uteamcore.coremod")
		attributes("FMLModType": "LIBRARY")
	}
}

signjar.sign(tasks.named("jar"))

configurations.runtimeElements.artifacts.clear()

artifacts {
	runtimeElements(tasks.named("jar")) {
		builtBy(tasks.named("signJar"))
	}
}

repositories {
	maven {
		url = "https://maven.neoforged.net/releases"
	}
	maven {
		url = "https://libraries.minecraft.net"
	}
	mavenCentral()
}

dependencies {
	compileOnly "net.neoforged.fancymodloader:loader:10.0.23"
	compileOnly "org.jetbrains:annotations:24.1.0"
}